# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Home
  #   url: 
  #   weight: 10
  - name: Lin Du
    url: people
    weight: 30
  # - name: Research
  #   url: research
  #   weight: 10
  - name: Publications
    url: publication
    weight: 40
  - name: Memories
    url: resources
    weight: 60
  - name: Contact
    url: contact
    weight: 70
  - name: News
    url: news
    weight: 50
